# Generated by Django 2.1.9 on 2020-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailData',
            fields=[
                ('Mail_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('User_ID', models.CharField(max_length=50)),
                ('User_Email', models.CharField(max_length=50)),
                ('To_Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
                ('MediaFile', models.FileField(upload_to='mediafiles/')),
            ],
            options={
                'db_table': 'MailData',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('User_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(default='None', max_length=50)),
                ('User_Email', models.CharField(max_length=50)),
                ('User_Phone', models.CharField(default='None', max_length=14)),
                ('User_Password', models.CharField(default='None', max_length=20)),
                ('Verify_Status', models.CharField(default='Unverified', max_length=20)),
                ('Status', models.CharField(default='Active', max_length=20)),
                ('Store_Logo', models.FileField(upload_to='mediafiles/')),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
