# Generated by Django 2.1.9 on 2020-07-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Store_Logo',
        ),
    ]
