# Generated by Django 2.1.9 on 2020-07-07 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userdata_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 7), max_length=15),
        ),
    ]
