# Generated by Django 2.1.9 on 2020-07-07 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_maildata_mail_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentData',
            fields=[
                ('Mail_Date', models.CharField(default=datetime.date(2020, 7, 7), max_length=15)),
                ('Mail_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('User_ID', models.CharField(max_length=50)),
                ('User_Email', models.CharField(max_length=50)),
                ('To_Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'SentData',
            },
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Message',
            field=models.CharField(max_length=500),
        ),
    ]
