# Generated by Django 2.1.9 on 2020-07-09 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200709_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='User_Date',
            field=models.CharField(default=datetime.date(2020, 7, 10), max_length=15),
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 10), max_length=15),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 10), max_length=15),
        ),
    ]
