# Generated by Django 2.1.9 on 2020-07-19 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200710_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Date', models.CharField(default='PL001', max_length=7)),
                ('User_ID', models.CharField(max_length=50)),
                ('Pay_ID', models.CharField(default='Not Availiable', max_length=20)),
            ],
            options={
                'db_table': 'UserPlanData',
            },
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 20), max_length=15),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 20), max_length=15),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='User_Date',
            field=models.CharField(default=datetime.date(2020, 7, 20), max_length=15),
        ),
    ]
