# Generated by Django 2.1.9 on 2020-07-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200720_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplandata',
            old_name='Plan_Date',
            new_name='Plan_ID',
        ),
    ]
