# Generated by Django 2.1.9 on 2020-07-21 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200720_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdata',
            name='MediaSize',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 21), max_length=15),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 21), max_length=15),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='User_Date',
            field=models.CharField(default=datetime.date(2020, 7, 21), max_length=15),
        ),
    ]
