# Generated by Django 2.1.9 on 2020-07-23 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200721_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayData',
            fields=[
                ('Pay_Date', models.DateTimeField(auto_now=True)),
                ('Pay_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Plan_ID', models.CharField(max_length=7)),
                ('User_ID', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Not Availiable', max_length=20)),
            ],
            options={
                'db_table': 'PayData',
            },
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('Pay_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CURRENCY', models.CharField(blank=True, default='None', max_length=100)),
                ('GATEWAYNAME', models.CharField(blank=True, default='None', max_length=100)),
                ('RESPMSG', models.CharField(blank=True, default='None', max_length=1000)),
                ('BANKNAME', models.CharField(blank=True, default='None', max_length=100)),
                ('PAYMENTMODE', models.CharField(blank=True, default='None', max_length=100)),
                ('RESPCODE', models.CharField(blank=True, default='None', max_length=100)),
                ('TXNID', models.CharField(blank=True, default='None', max_length=100)),
                ('TXNAMOUNT', models.CharField(blank=True, default='None', max_length=100)),
                ('STATUS', models.CharField(blank=True, default='None', max_length=100)),
                ('BANKTXNID', models.CharField(blank=True, default='None', max_length=100)),
                ('TXNDATE', models.CharField(blank=True, default='None', max_length=100)),
                ('CHECKSUMHASH', models.CharField(blank=True, default='None', max_length=100)),
            ],
            options={
                'db_table': 'PaymentData',
            },
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 24), max_length=15),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 24), max_length=15),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='User_Date',
            field=models.CharField(default=datetime.date(2020, 7, 24), max_length=15),
        ),
    ]
