# Generated by Django 2.1.9 on 2020-07-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200724_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdata',
            name='Subject',
            field=models.CharField(default='no-subject', max_length=200),
        ),
    ]
