# Generated by Django 2.1.9 on 2020-07-25 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sentdata_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitemap', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Sitemap',
            },
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 25), max_length=15),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 25), max_length=15),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='User_Date',
            field=models.CharField(default=datetime.date(2020, 7, 25), max_length=15),
        ),
    ]
