# Generated by Django 2.1.9 on 2020-07-29 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200725_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildata',
            name='ciphertext',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='maildata',
            name='nonce',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='maildata',
            name='tag',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 29), max_length=15),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 29), max_length=15),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='User_Date',
            field=models.CharField(default=datetime.date(2020, 7, 29), max_length=15),
        ),
    ]
