# Generated by Django 2.1.9 on 2020-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200729_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildata',
            name='key',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
