# Generated by Django 2.1.9 on 2020-07-30 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_maildata_key1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maildata',
            name='ciphertext',
        ),
        migrations.RemoveField(
            model_name='maildata',
            name='key1',
        ),
        migrations.RemoveField(
            model_name='maildata',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='maildata',
            name='tag',
        ),
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 30), max_length=15),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.CharField(default=datetime.date(2020, 7, 30), max_length=15),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='User_Date',
            field=models.CharField(default=datetime.date(2020, 7, 30), max_length=15),
        ),
    ]
