# Generated by Django 2.1.9 on 2020-10-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201020_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildata',
            name='Mail_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sentdata',
            name='Mail_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='User_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
